version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=demo_pass
    volumes:
      - /data/mysql
  boa-app:
    image: repo/banking-app
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    ports:
      - 6070:6060
    volumes:
      - /data/compose-app